# Generated by Django 4.2.3 on 2023-07-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piece', '0002_alter_piece_qts'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='piece_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
