# Generated by Django 4.2.3 on 2023-08-01 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0003_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
