# Generated by Django 4.2.3 on 2023-08-02 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0006_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
