# Generated by Django 4.2.3 on 2023-07-16 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('piece', '0002_alter_piece_qts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Panierpieces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qts', models.PositiveIntegerField(default=1)),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piece.piece')),
            ],
        ),
    ]
